export const AlertsData = {
  TechnicalAlert: {
    SMA: {
      name: "Simple Moving Average (SMA) alerts",
      description: "SMA price cross alerts",
      data: [
        {
          title: "Price crossed below SMA(50)",
          script: "CROSS(MA(C, 50), C)",
          description: "Crosing Price is crossed blow SMA50",
          param: [],
          type: "Technical",
        },
        {
          title: "Price crossed below SMA(N)",
          script: "CROSS(MA(C, N), C)",
          description: "Crosing Price is crossed blow SMA(N)",
          param: [{ name: "N", value: 0 }],
          type: "Technical",
        },
        {
          title: "Price crossed above SMA(50)",
          script: "CROSS(C, MA(C, 50))",
          description: "Crosing Price is crossed above SMA50",
          param: [],
          type: "Technical",
        },
        {
          title: "Price crossed above SMA(N)",
          script: "CROSS(C, MA(C, N))",
          description: "Crosing Price is crossed above SMA(N)",
          param: [{ name: "N", value: 0 }],
          type: "Technical",
        },
        {
          title: "Price Moved 20% below SMA50",
          script: "CROSS(20, (((MA(C, 50) - C) / (MA(C, 50))) * 100 ))",
          description: "Crosing Price is moved blow SMA50",
          param: [],
          type: "Technical",
        },
        {
          title: "Price Moved (N1)% below SMA(N2)",
          script: "CROSS(N1, (((MA(C, N2) - C) / (MA(C, N2))) * 100 ))",
          description: "Crosing Price is moved (N1)% blow SMA(N2)",
          param: [
            { name: "N1", value: 0 },
            { name: "N2", value: 0 },
          ],
          type: "Technical",
        },
        {
          title: "SMA20 crossed SMA50 above",
          script: "CROSS(MA(C, 20), MA(C, 50))",
          description: "SMA20 is crossed SMA50 above",
          param: [],
          type: "Technical",
        },
        {
          title: "SMA(N1) crossed SMA(N2) above",
          script: "CROSS(MA(C, N1), MA(C, N2))",
          description: "SMA(N1) is crossed SMA(N2) above",
          param: [
            { name: "N1", value: 0 },
            { name: "N2", value: 0 },
          ],
          type: "Technical",
        },
        {
          title: "SMA20 crossed SMA50 below",
          script: "CROSS(MA(C, 50), MA(C, 20))",
          description: "SMA20 is crossed SMA50 below",
          param: [],
          type: "Technical",
        },
        {
          title: "SMA(N1) crossed SMA(N2) below",
          script: "CROSS(MA(C, N1), MA(C, N2))",
          description: "SMA(N1) is crossed SMA(N2) below",
          param: [
            { name: "N1", value: 0 },
            { name: "N2", value: 0 },
          ],
          type: "Technical",
        },
      ],
    },
    EMA: {
      name: "Exponential Moving Average (EMA) alerts",
      description: "EMA price cross alerts",
      data: [
        {
          title: "Price crossed below EMA(50)",
          script: "CROSS(EMA(C, 50), C)",
          description: "Crosing Price is crossed blow EMA50",
          param: [],
          type: "Technical",
        },
        {
          title: "Price crossed below EMA(N)",
          script: "CROSS(EMA(C, N), C)",
          description: "Crosing Price is crossed blow EMA(N)",
          param: [{ name: "N", value: 0 }],
          type: "Technical",
        },
        {
          title: "Price crossed above EMA(50)",
          script: "CROSS(C, EMA(C, 50))",
          description: "Crosing Price is crossed above EMA50",
          param: [],
          type: "Technical",
        },
        {
          title: "Price crossed above EMA(N)",
          script: "CROSS(C, EMA(C, N))",
          description: "Crosing Price is crossed above EMA(N)",
          param: [{ name: "N", value: 0 }],
          type: "Technical",
        },
        {
          title: "Price Moved 20% below EMA50",
          script: "CROSS(20, (((EMA(C, 50) - C) / (EMA(C, 50))) * 100 ))",
          description: "Crosing Price is moved blow EMA50",
          param: [],
          type: "Technical",
        },
        {
          title: "Price Moved (N1)% below EMA(N2)",
          script: "CROSS(N1, (((EMA(C, N2) - C) / (EMA(C, N2))) * 100 ))",
          description: "Crosing Price is moved (N1)% blow EMA(N2)",
          param: [
            { name: "N1", value: 0 },
            { name: "N2", value: 0 },
          ],
          type: "Technical",
        },
        {
          title: "EMA20 crossed EMA50 above",
          script: "CROSS(EMA(C, 20), EMA(C, 50))",
          description: "EMA20 is crossed EMA50 above",
          param: [],
          type: "Technical",
        },
        {
          title: "EMA(N1) crossed EMA(N2) above",
          script: "CROSS(EMA(C, N1), EMA(C, N2))",
          description: "EMA(N1) is crossed EMA(N2) above",
          param: [
            { name: "N1", value: 0 },
            { name: "N2", value: 0 },
          ],
          type: "Technical",
        },
        {
          title: "EMA20 crossed EMA50 below",
          script: "CROSS(EMA(C, 50), EMA(C, 20))",
          description: "EMA20 is crossed EMA50 below",
          param: [],
          type: "Technical",
        },
        {
          title: "EMA(N1) crossed EMA(N2) below",
          script: "CROSS(EMA(C, N1), EMA(C, N2))",
          description: "EMA(N1) is crossed EMA(N2) below",
          param: [
            { name: "N1", value: 0 },
            { name: "N2", value: 0 },
          ],
          type: "Technical",
        },
      ],
    },
  },
  PriceAlert: {
    name: "Stock Price alerts",
    description: "Stock Price Alerts",
    data: [
      {
        title: "New 52 Week High",
        script: "CROSS(H, hhv(c, 260))",
        description: "For new 52 weeks, High price",
        param: [],
        type: "Price",
      },
      {
        title: "New N Week High",
        script: "CROSS(H, hhv(c, N))",
        description: "For new N weeks, High price",
        param: [{ name: "N", value: 0 }],
        type: "Price",
      },
      {
        title: "New 52 Week Low",
        script: "CROSS(LLV(L, 260), L)",
        description: "For new 52 weeks, Low price",
        param: [],
        type: "Price",
      },
      {
        title: "New N Week Low",
        script: "CROSS(LLV(L, N), L)",
        description: "For new N weeks, Low price",
        param: [{ name: "N", value: 0 }],
        type: "Price",
      },
      {
        title: "New 52 Week Closing High",
        script: "CROSS(C, hhv(c, 260))",
        description: "Crosing Price is high for 52 weeks",
        param: [],
        type: "Price",
      },
      {
        title: "New N Week Closing High",
        script: "CROSS(H, hhv(c, N))",
        description: "Crosing Price is high for N weeks",
        param: [{ name: "N", value: 0 }],
        type: "Price",
      },
      {
        title: "New 52 Week Closing Low",
        script: "CROSS(LLV(L, 260), C)",
        description: "Crosing Price is low for 52 weeks",
        param: [],
        type: "Price",
      },
      {
        title: "New N Week Closing Low",
        script: "CROSS(LLV(L, N), C)",
        description: "Crosing Price is low for N weeks",
        param: [{ name: "N", value: 0 }],
        type: "Price",
      },
    ],
  },
};
